# Generated by Django 2.1.15 on 2022-12-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_insert_resmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='signin_resdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
