# Generated by Django 2.1.15 on 2022-12-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_signin_resdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insert_resmenu',
            old_name='r_address',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='insert_resmenu',
            old_name='r_phone_number',
            new_name='Price',
        ),
        migrations.RemoveField(
            model_name='insert_resmenu',
            name='r_city',
        ),
        migrations.RemoveField(
            model_name='insert_resmenu',
            name='r_country',
        ),
        migrations.RemoveField(
            model_name='insert_resmenu',
            name='r_name',
        ),
        migrations.RemoveField(
            model_name='insert_resmenu',
            name='r_password',
        ),
    ]
