# Generated by Django 2.1.15 on 2022-12-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20221207_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='insert_resmenu',
            name='r_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
