# Generated by Django 2.1.15 on 2022-12-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_insert_resmenu_r_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insert_resmenu',
            name='r_name',
        ),
    ]
