# Generated by Django 2.1.15 on 2022-12-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_remove_insert_resmenu_r_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_page_display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Item', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
