# Generated by Django 2.1.15 on 2022-12-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_auto_20221209_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_page_display',
            old_name='r_emailid',
            new_name='emailid',
        ),
    ]
