# Generated by Django 2.1.15 on 2022-12-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0011_auto_20221209_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='insert_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=100)),
                ('Item', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
