# Generated by Django 2.1.15 on 2022-12-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0013_insert_cart_r_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=100)),
                ('Item', models.CharField(max_length=100)),
            ],
        ),
    ]
