# Generated by Django 2.1.15 on 2022-12-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_search_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='res_menu_page_display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_emailid', models.CharField(max_length=100)),
            ],
        ),
    ]
